
--liquibase formatted sql

--changeset burgasvv:1
create table if not exists department (
    id bigint generated by default as identity unique not null ,
    name varchar unique not null ,
    description text unique not null
);

--changeset burgasvv:2
begin ;
insert into department(name, description) values ('Отдел Кадров', 'Описание Отдела Кадров');
insert into department(name, description) values ('Отдел Склад', 'Описание Отдела Склад');
insert into department(name, description) values ('Отдел Выпуска', 'Описание Отдела Выпуска');
commit ;