
--liquibase formatted sql

--changeset burgasvv:1
create table if not exists employee (
    id bigint generated by default as identity unique not null ,
    name varchar not null ,
    surname varchar not null ,
    patronymic varchar not null ,
    department_id bigint references department(id) on delete set null on update cascade
);