
--liquibase formatted sql

--changeset burgasvv:1
create table if not exists category (
    id bigint generated by default as identity unique not null ,
    name varchar unique not null ,
    description text unique not null
);

--changeset burgasvv:2
begin ;
insert into category(name, description) values ('Ноутбук','Описание категории Ноутбук');
insert into category(name, description) values ('Смартфон','Описание категории Смартфон');
insert into category(name, description) values ('Персональный Компьютер','Описание категории Персональный Компьютер');
insert into category(name, description) values ('Планшет','Описание категории Планшет');
commit ;