
--liquibase formatted sql

--changeset burgasvv:1
create table if not exists product (
    id bigint generated by default as identity unique not null ,
    category_id bigint references category(id) on delete set null on update cascade ,
    model varchar unique not null ,
    characteristics text not null ,
    price decimal not null check ( price > 0 )
);